# Generated by Django 5.1.2 on 2024-12-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_products', '0003_delete_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='wishes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
